# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dossier < Formula
  desc "Keyboard-driven TUI for navigating OpenSpec project artifacts"
  homepage "https://github.com/fselich/dossier"
  version "0.10.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/dossier/releases/download/v0.10.0/dossier-linux-amd64.tar.gz"
    sha256 "d93bcda127c68f357aedf8e4a6c3420890effa3ee321ad2d479182b6a0ee749b"
    define_method(:install) do
      bin.install "dossier"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/dossier/releases/download/v0.10.0/dossier-linux-arm64.tar.gz"
    sha256 "d23d3b5b2cbc09bb9b37e2e27d0a985bba5424a74c93fd2c3c1aca9dc2744ea8"
    define_method(:install) do
      bin.install "dossier"
    end
  end

  test do
    system "#{bin}/dossier", "--help"
  end
end
