# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smm < Formula
  desc "Terminal User Interface for Google Cloud Platform secret management"
  homepage "https://github.com/fselich/smm"
  version "0.1.11"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/smm/releases/download/v0.1.11/smm-linux-amd64.tar.gz"
    sha256 "b37c6fa2f3b204cb3c8bf8acc2c737122c6e2f3ce82e030650ab3487edda701a"
    def install
      bin.install "smm"
    end
  end
  if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/smm/releases/download/v0.1.11/smm-linux-arm64.tar.gz"
    sha256 "697d861f2762f7999c97ab90c599dab01fbfb6c2d4e20b29ad4715bd22ca55f0"
    def install
      bin.install "smm"
    end
  end

  test do
    system "#{bin}/smm", "--help"
  end
end
