# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Smm < Formula
  desc "Terminal User Interface for Google Cloud Platform secret management"
  homepage "https://github.com/fselich/smm"
  version "0.3.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/smm/releases/download/v0.3.0/smm-linux-amd64.tar.gz"
    sha256 "f129b287a752b8426d5c52227a507f29d0f0de86a8098ad998ddb786e7478903"
    define_method(:install) do
      bin.install "smm"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/fselich/smm/releases/download/v0.3.0/smm-linux-arm64.tar.gz"
    sha256 "57efd70dfeadad83f336400e1dbc7e4bbb5a54cc73891de13c4eab01f7ca55ee"
    define_method(:install) do
      bin.install "smm"
    end
  end

  test do
    system "#{bin}/smm", "--help"
  end
end
